### PR TITLE
Added Comments

### PR DESCRIPTION
**Pull request by shreyakhetani**

### CODE REVIEW

**Review by karljan456 — COMMENTED** [review]
Good!

**Review by marikadu — APPROVED** [review]
Nice comments!

**Review by dadaJunglist — CHANGES_REQUESTED** [review]
Please, add one more line of code

**Comment by karljan456** [comment]
Nice

**Review by karljan456 — APPROVED** [review]
It works!

**Review by marikadu — APPROVED** [review]
Good

**Review by dadaJunglist — COMMENTED** [review]
thanks for comments

**Review by dadaJunglist — APPROVED** [review]

**Pull request merged**
